In [2]:
import pandas as pd

In [8]:
neww = pd.read_csv("new_stats.csv")
new3 = neww["Team"].unique()
new3.sort()

usage = pd.DataFrame({"Team" : new3,
                      "Avg Usage" : round(neww.groupby("Team")["USG%"].mean(), 1),
                      "Max Usage" : neww.groupby("Team")["USG%"].max()})
usage.reset_index(drop = True, inplace = True)

In [9]:
usage.sort_values("Max Usage", ascending = False)

    Team  Avg Usage  Max Usage
12   HOU       22.1       40.5
24   PHI       20.8       33.3
25   PHO       21.1       32.9
14   LAC       23.3       32.4
18   MIL       20.3       32.3
11  GSW2       20.0       31.9
10   GSW       18.3       31.9
31   UTA       22.9       31.6
15   LAL       22.7       31.6
3    BOS       21.2       31.5
16   MEM       20.9       31.4
7    DAL       21.8       31.0
5    CHI       21.2       30.5
32   WAS       20.5       30.4
33  WAS2       22.8       30.4
9    DET       22.4       30.2
1    BKN       20.9       29.6
2   BKN2       22.5       29.6
27  POR2       22.4       29.3
26   POR       21.9       29.3
19   MIN       19.8       28.9
0    ATL       21.1       28.4
23   ORL       20.4       28.0
13   IND       21.9       27.9
29   SAS       21.7       27.9
21   NYK       21.6       27.8
6    CLE       21.5       27.6
8    DEN       21.1       27.4
20   NOP       19.8       25.4
28   SAC       21.0       25.1
22   OKC       18.5       24.2
17   MIA       19.9       23.7
30   TOR       19.7       22.9
4    CHA       15.8       18.6